# SZU-Dlib

In [8]:
import cv2
import numpy as np
import dlib

## Facial Landmark Detection

In [9]:
def shape_to_np(shape, dtype="int"):
	# initialize the list of (x, y)-coordinates
	coords = np.zeros((shape.num_parts, 2), dtype=dtype)
	# loop over all facial landmarks and convert them
	# to a 2-tuple of (x, y)-coordinates
	for i in range(0, shape.num_parts):
		coords[i] = (shape.part(i).x, shape.part(i).y)
	# return the list of (x, y)-coordinates
	return coords

def detect_facial_landmarks(img):
    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor('/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/01-DlibTest/shape_predictor_68_face_landmarks.dat')
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    rects = detector(gray, 1)

    for index, rect in enumerate(rects):
        lm_points = predictor(gray, rect)
        lm_points = shape_to_np(lm_points)
    return lm_points

def test_01():
    img = cv2.imread('/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/01-DlibTest/donald_trump.jpg')
    lm_points = detect_facial_landmarks(img)
    vis_img = img.copy()
    for (x,y) in lm_points:
        cv2.circle(vis_img, (x,y), 2, (0,0,255), -1)
#         f = open('/Users/zhaoxuyan/Desktop/1.txt','a')
#         str1 = x + " " + y
#         f.write(str1)
#         f.close()
    cv2.imshow('', vis_img)
    cv2.imwrite('/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/01-DlibTest/resutl.jpg',vis_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [14]:
test_01()

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

## Delaunay Triangulation

In [10]:
import cv2
import numpy as np
import random

# Check if a point is inside a rectangle
def rect_contains(rect, point) :
    if point[0] < rect[0] :
        return False
    elif point[1] < rect[1] :
        return False
    elif point[0] > rect[2] :
        return False
    elif point[1] > rect[3] :
        return False
    return True

# Draw a point
def draw_point(img, p, color ) :
    cv2.circle( img, p, 2, color, cv2.FILLED, cv2.LINE_AA, 0 )


# Draw delaunay triangles
def draw_delaunay(img, subdiv, delaunay_color ) :

    triangleList = subdiv.getTriangleList();
    print(triangleList)
    size = img.shape
    r = (0, 0, size[1], size[0])

    for t in triangleList :
        
        pt1 = (t[0], t[1])
        pt2 = (t[2], t[3])
        pt3 = (t[4], t[5])
        
        if rect_contains(r, pt1) and rect_contains(r, pt2) and rect_contains(r, pt3) :
        
            cv2.line(img, pt1, pt2, delaunay_color, 1, cv2.LINE_AA, 0)
            cv2.line(img, pt2, pt3, delaunay_color, 1, cv2.LINE_AA, 0)
            cv2.line(img, pt3, pt1, delaunay_color, 1, cv2.LINE_AA, 0)


# Draw voronoi diagram
def draw_voronoi(img, subdiv) :

    ( facets, centers) = subdiv.getVoronoiFacetList([])

    for i in range(0,len(facets)) :
        ifacet_arr = []
        for f in facets[i] :
            ifacet_arr.append(f)
        
        ifacet = np.array(ifacet_arr, np.int)
        color = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))

        cv2.fillConvexPoly(img, ifacet, color, cv2.LINE_AA, 0);
        ifacets = np.array([ifacet])
        cv2.polylines(img, ifacets, True, (0, 0, 0), 1, cv2.LINE_AA, 0)
        cv2.circle(img, (centers[i][0], centers[i][1]), 3, (0, 0, 0), cv2.FILLED, cv2.LINE_AA, 0)


def test_02():
    # Define window names
    win_delaunay = "Delaunay Triangulation"
    win_voronoi = "Voronoi Diagram"

    # Turn on animation while drawing triangles
    animate = True
    
    # Define colors for drawing.
    delaunay_color = (255,255,255)
    points_color = (0, 0, 255)

    # Read in the image.
    img = cv2.imread("/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/02-Delaunay/obama.jpg");
    
    # Keep a copy around
    img_orig = img.copy();
    
    # Rectangle to be used with Subdiv2D
    size = img.shape
    rect = (0, 0, size[1], size[0])
    
    # Create an instance of Subdiv2D
    subdiv = cv2.Subdiv2D(rect);

    # Create an array of points.
    points = [];
    
    # Read in the points from a text file
#     with open("/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/02-Delaunay/obama.txt") as file :
#         for line in file :
#             x, y = line.split()
#             points.append((int(x), int(y)))
  
    # 提取关键点
    img = cv2.imread('/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/02-Delaunay/obama.jpg')
    lm_points = detect_facial_landmarks(img)
    vis_img = img.copy()
    for (x,y) in lm_points:
        points.append((int(x), int(y)))

    # Insert points into subdiv
    for p in points :
        subdiv.insert(p)
        
        # Show animation
        if animate :
            img_copy = img_orig.copy()
            # Draw delaunay triangles
            draw_delaunay( img_copy, subdiv, (255, 255, 255) );
            cv2.imshow(win_delaunay, img_copy)
            cv2.waitKey(100)

    # Draw delaunay triangles
    draw_delaunay( img, subdiv, (255, 255, 255) );

    # Draw points
    for p in points :
        draw_point(img, p, (0,0,255))

    # Allocate space for voronoi Diagram
    img_voronoi = np.zeros(img.shape, dtype = img.dtype)

    # Draw voronoi diagram
    draw_voronoi(img_voronoi,subdiv)

    # Show results
    cv2.imshow(win_delaunay,img)
    cv2.imwrite('/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/02-Delaunay/result_win_delaunay.jpg',img)
    cv2.imshow(win_voronoi,img_voronoi)
    cv2.imwrite('/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/02-Delaunay/result_win_voronoi.jpg',img_voronoi)
    cv2.waitKey(0)

In [ ]:
test_02()

[[ 2091.     0.     0.  2091.   209.   243.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   209.   243.]
 [-2091. -2091.  2091.     0.   209.   243.]]
[[ 2091.     0.     0.  2091.   212.   271.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   212.   271.]
 [-2091. -2091.  2091.     0.   209.   243.]
 [  209.   243.  2091.     0.   212.   271.]
 [  212.   271. -2091. -2091.   209.   243.]]
[[ 2091.     0.     0.  2091.   216.   299.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   209.   243.]
 [  209.   243.  2091.     0.   216.   299.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243.   216.   299.   212.   271.]]
[[ 2091.     0.     0.  2091.   221.   324.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   209.   243.]
 [  209

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   209.   243.]
 [  209.   243.  2091.     0.   397.   320.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  355.   390.   261.   395.   242.   374.]
 [  261.   395.   355.   390.   333.   409.]
 [  212.   271.   209.   243.   397.   320.]
 [  261.   395.   333.   409.   307.   416.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   397.   320.]
 [  261.   395.   307.   416.   281.   412.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   397.   320.]
 [  355.   390.   242.   374.   374.   369.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   388.   345.]
 [  374.   369.   242.   374.   229.   351.]
 [    0.  2091.   242.   374.   261.   395.]
 [  374.   369.   229.   351.   388.   345.]
 [    0.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   407.   235.]
 [  251.   219.   216.   299.   212.   271.]
 [  216.   299.   251.   219.   397.   320.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  355.   390.   261.   395.   242.   374.]
 [  261.   395.   355.   390.   333.   409.]
 [  212.   271.   209.   243.   223.   239.]
 [  261.   395.   333.   409.   307.   416.]
 [    0.  2091.   216.   299.   221.   324.]
 [  261.   395.   307.   416.   281.   412.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   397.   320.]
 [  355.   390.   242.   374.   374.   369.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   388.   345.]
 [  374.   369.   242.   374.   229.   351.]
 [    0.  2091.   242.   374.   261.   395.]
 [  374.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  270.   219.   212.   271.   223.   239.]
 [  212.   271.   270.   219.   289.   223.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  355.   390.   261.   395.   242.   374.]
 [  261.   395.   355.   390.   333.   409.]
 [  212.   271.   209.   243.   223.   239.]
 [  261.   395.   333.   409.   307.   416.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   289.   223.]
 [  261.   395.   307.   416.   281.   412.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   289.   223.]
 [  355.   390.   242.   374.   374.   369.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   388.   345.]
 [  374.   369.   242.   374.   229.   351.]
 [    0.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  303.   258.   270.   219.   289.   223.]
 [  270.   219.   303.   258.   251.   219.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  355.   390.   261.   395.   303.   277.]
 [  261.   395.   355.   390.   333.   409.]
 [  212.   271.   209.   243.   223.   239.]
 [  261.   395.   333.   409.   307.   416.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   303.   277.]
 [  261.   395.   307.   416.   281.   412.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   303.   277.]
 [  303.   277.   261.   395.   242.   374.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   303.   277.]
 [  374.   369.   303.   277.   388.   345.]
 [  303.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  303.   258.   270.   219.   289.   223.]
 [  270.   219.   303.   258.   251.   219.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  303.   314.   307.   416.   261.   395.]
 [  307.   416.   303.   314.   333.   409.]
 [  212.   271.   209.   243.   223.   239.]
 [  292.   313.   261.   395.   242.   374.]
 [  261.   395.   292.   313.   303.   314.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   281.   311.]
 [  261.   395.   307.   416.   281.   412.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  292.   313.   242.   374.   281.   311.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   281.   311.]
 [  397.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  254.   240.   303.   258.   303.   277.]
 [  303.   258.   254.   240.   289.   223.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  303.   314.   307.   416.   261.   395.]
 [  307.   416.   303.   314.   333.   409.]
 [  212.   271.   209.   243.   223.   239.]
 [  292.   313.   261.   395.   242.   374.]
 [  261.   395.   292.   313.   303.   314.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   244.   246.]
 [  261.   395.   307.   416.   281.   412.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  292.   313.   242.   374.   281.   311.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   281.   311.]
 [  374.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  303.   314.   307.   416.   261.   395.]
 [  307.   416.   303.   314.   333.   409.]
 [  212.   271.   209.   243.   223.   239.]
 [  292.   313.   261.   395.   242.   374.]
 [  261.   395.   292.   313.   303.   314.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  261.   395.   307.   416.   281.   412.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  292.   313.   242.   374.   281.   311.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   281.   311.]
 [  374.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  303.   314.   307.   416.   261.   395.]
 [  307.   416.   303.   314.   333.   409.]
 [  212.   271.   209.   243.   223.   239.]
 [  292.   313.   261.   395.   242.   374.]
 [  261.   395.   292.   313.   303.   314.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  261.   395.   307.   416.   281.   412.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  292.   313.   242.   374.   281.   311.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   281.   311.]
 [  374.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  303.   314.   307.   416.   261.   395.]
 [  307.   416.   303.   314.   333.   409.]
 [  212.   271.   209.   243.   223.   239.]
 [  292.   313.   261.   395.   242.   374.]
 [  261.   395.   292.   313.   303.   314.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  261.   395.   307.   416.   281.   412.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  292.   313.   242.   374.   281.   311.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   281.   311.]
 [  374.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  307.   416.   278.   341.   333.   409.]
 [  278.   341.   307.   416.   281.   412.]
 [  212.   271.   209.   243.   223.   239.]
 [  278.   341.   292.   313.   303.   314.]
 [  292.   313.   278.   341.   281.   311.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  261.   395.   278.   341.   281.   412.]
 [  278.   341.   261.   395.   262.   346.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  262.   346.   261.   395.   242.   374.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  278.   341.   304.   339.   261.   395.]
 [  304.   339.   278.   341.   293.   336.]
 [  212.   271.   209.   243.   223.   239.]
 [  281.   311.   293.   336.   278.   341.]
 [  293.   336.   281.   311.   292.   313.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  278.   341.   261.   395.   262.   346.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  262.   346.   261.   395.   242.   374.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   262.   346.]
 [  374.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  278.   341.   304.   339.   261.   395.]
 [  304.   339.   278.   341.   293.   336.]
 [  212.   271.   209.   243.   223.   239.]
 [  281.   311.   293.   336.   278.   341.]
 [  293.   336.   281.   311.   292.   313.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  278.   341.   261.   395.   262.   346.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  262.   346.   261.   395.   242.   374.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   262.   346.]
 [  326.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  278.   341.   304.   339.   261.   395.]
 [  304.   339.   278.   341.   293.   336.]
 [  212.   271.   209.   243.   223.   239.]
 [  281.   311.   293.   336.   278.   341.]
 [  293.   336.   281.   311.   292.   313.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  278.   341.   261.   395.   262.   346.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  262.   346.   261.   395.   242.   374.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.   351.   221.   324.   262.   346.]
 [  326.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  293.   336.   305.   361.   278.   341.]
 [  305.   361.   293.   336.   304.   339.]
 [  212.   271.   209.   243.   223.   239.]
 [  281.   311.   293.   336.   278.   341.]
 [  293.   336.   281.   311.   292.   313.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  262.   346.   305.   361.   261.   395.]
 [  305.   361.   262.   346.   278.   341.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  262.   346.   261.   395.   242.   374.]
 [    0.  2091.   229.   351.   242.   374.]
 [  229.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  304.   339.   293.   361.   293.   336.]
 [  293.   361.   304.   339.   305.   361.]
 [  212.   271.   209.   243.   223.   239.]
 [  281.   311.   293.   336.   278.   341.]
 [  293.   336.   281.   311.   292.   313.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  278.   341.   293.   361.   278.   356.]
 [  293.   361.   278.   341.   293.   336.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  278.   356.   242.   374.   262.   346.]
 [  242.   374.   278.   356.   261.   395.]
 [    0.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  305.   361.   292.   346.   304.   339.]
 [  292.   346.   305.   361.   293.   361.]
 [  212.   271.   209.   243.   223.   239.]
 [  281.   311.   293.   336.   278.   341.]
 [  293.   336.   281.   311.   292.   313.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  292.   346.   278.   356.   278.   341.]
 [  278.   356.   292.   346.   293.   361.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  278.   356.   242.   374.   262.   346.]
 [  242.   374.   278.   356.   261.   395.]
 [    0.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  293.   361.   304.   347.   305.   361.]
 [  304.   347.   293.   361.   292.   346.]
 [  212.   271.   209.   243.   223.   239.]
 [  281.   311.   293.   336.   278.   341.]
 [  293.   336.   281.   311.   292.   313.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  292.   346.   278.   356.   278.   341.]
 [  278.   356.   292.   346.   293.   361.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  278.   356.   242.   374.   262.   346.]
 [  242.   374.   278.   356.   261.   395.]
 [    0.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  293.   361.   304.   347.   305.   361.]
 [  304.   347.   293.   361.   292.   346.]
 [  212.   271.   209.   243.   223.   239.]
 [  281.   311.   293.   336.   278.   341.]
 [  293.   336.   281.   311.   292.   313.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  292.   346.   278.   356.   278.   341.]
 [  278.   356.   292.   346.   293.   361.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  278.   356.   242.   374.   262.   346.]
 [  242.   374.   278.   356.   261.   395.]
 [    0.  

[[ 2091.     0.     0.  2091.   355.   390.]
 [    0.  2091.  2091.     0. -2091. -2091.]
 [    0.  2091. -2091. -2091.   216.   299.]
 [-2091. -2091.  2091.     0.   357.   214.]
 [  267.   248.   254.   240.   267.   238.]
 [  254.   240.   267.   248.   254.   249.]
 [-2091. -2091.   212.   271.   216.   299.]
 [  212.   271. -2091. -2091.   209.   243.]
 [  209.   243. -2091. -2091.   233.   225.]
 [  304.   347.   293.   347.   304.   339.]
 [  293.   347.   304.   347.   304.   348.]
 [  212.   271.   209.   243.   223.   239.]
 [  281.   311.   293.   336.   278.   341.]
 [  293.   336.   281.   311.   292.   313.]
 [    0.  2091.   216.   299.   221.   324.]
 [  216.   299.   212.   271.   254.   249.]
 [  292.   346.   278.   356.   278.   341.]
 [  278.   356.   292.   346.   293.   347.]
 [    0.  2091.   221.   324.   229.   351.]
 [  221.   324.   216.   299.   281.   311.]
 [  278.   356.   242.   374.   262.   346.]
 [  242.   374.   278.   356.   261.   395.]
 [    0.  

## Face Morph

In [1]:
import numpy as np
import cv2
import sys

# Read points from text file
def readPoints(path) :
    # Create an array of points.
    points = [];
    # Read points
    with open(path) as file :
        for line in file :
            x, y = line.split()
            points.append((int(x), int(y)))

    return points

# Apply affine transform calculated using srcTri and dstTri to src and
# output an image of size.
def applyAffineTransform(src, srcTri, dstTri, size) :
    
    # Given a pair of triangles, find the affine transform.
    warpMat = cv2.getAffineTransform( np.float32(srcTri), np.float32(dstTri) )
    
    # Apply the Affine Transform just found to the src image
    dst = cv2.warpAffine( src, warpMat, (size[0], size[1]), None, flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REFLECT_101 )

    return dst


# Warps and alpha blends triangular regions from img1 and img2 to img
def morphTriangle(img1, img2, img, t1, t2, t, alpha) :

    # Find bounding rectangle for each triangle
    r1 = cv2.boundingRect(np.float32([t1]))
    r2 = cv2.boundingRect(np.float32([t2]))
    r = cv2.boundingRect(np.float32([t]))


    # Offset points by left top corner of the respective rectangles
    t1Rect = []
    t2Rect = []
    tRect = []


    for i in range(0, 3):
        tRect.append(((t[i][0] - r[0]),(t[i][1] - r[1])))
        t1Rect.append(((t1[i][0] - r1[0]),(t1[i][1] - r1[1])))
        t2Rect.append(((t2[i][0] - r2[0]),(t2[i][1] - r2[1])))


    # Get mask by filling triangle
    mask = np.zeros((r[3], r[2], 3), dtype = np.float32)
    cv2.fillConvexPoly(mask, np.int32(tRect), (1.0, 1.0, 1.0), 16, 0);

    # Apply warpImage to small rectangular patches
    img1Rect = img1[r1[1]:r1[1] + r1[3], r1[0]:r1[0] + r1[2]]
    img2Rect = img2[r2[1]:r2[1] + r2[3], r2[0]:r2[0] + r2[2]]

    size = (r[2], r[3])
    warpImage1 = applyAffineTransform(img1Rect, t1Rect, tRect, size)
    warpImage2 = applyAffineTransform(img2Rect, t2Rect, tRect, size)

    # Alpha blend rectangular patches
    imgRect = (1.0 - alpha) * warpImage1 + alpha * warpImage2

    # Copy triangular region of the rectangular patch to the output image
    img[r[1]:r[1]+r[3], r[0]:r[0]+r[2]] = img[r[1]:r[1]+r[3], r[0]:r[0]+r[2]] * ( 1 - mask ) + imgRect * mask


def test_03():

    filename1 = '/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/03-FaceMorph/hillary_clinton.jpg'
    filename2 = '/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/03-FaceMorph/ted_cruz.jpg'
    alpha = 0.5
    
    # Read images
    # img1 = cv2.imread(filename1);
    # img2 = cv2.imread(filename2);
    
    points1 = [];
    img1 = cv2.imread(filename1);
    lm_points1 = detect_facial_landmarks(img1)
    vis_img1 = img1.copy()
    for (x,y) in lm_points:
        points1.append((int(x), int(y)))
        
    points2 = [];
    img2 = cv2.imread(filename2);
    lm_points2 = detect_facial_landmarks(img2)
    vis_img2 = img2.copy()
    for (x,y) in lm_points2:
        points2.append((int(x), int(y)))
    
    # Convert Mat to float data type
    img1 = np.float32(img1)
    img2 = np.float32(img2)

    # Read array of corresponding points
    # points1 = readPoints(filename1 + '.txt')
    # points2 = readPoints(filename2 + '.txt')
    points = [];

    # Compute weighted average point coordinates
    for i in range(0, len(points1)):
        x = ( 1 - alpha ) * points1[i][0] + alpha * points2[i][0]
        y = ( 1 - alpha ) * points1[i][1] + alpha * points2[i][1]
        points.append((x,y))


    # Allocate space for final output
    imgMorph = np.zeros(img1.shape, dtype = img1.dtype)

    # Read triangles from tri.txt
    with open("/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/03-FaceMorph/tri.txt") as file :
        for line in file :
            x,y,z = line.split()
            
            x = int(x)
            y = int(y)
            z = int(z)
            
            t1 = [points1[x], points1[y], points1[z]]
            t2 = [points2[x], points2[y], points2[z]]
            t = [ points[x], points[y], points[z] ]

            # Morph one triangle at a time.
            morphTriangle(img1, img2, imgMorph, t1, t2, t, alpha)


    # Display Result
    cv2.imshow("Morphed Face", np.uint8(imgMorph))
    cv2.imwrite('/Users/zhaoxuyan/Desktop/SZU DeepLearning/day02-Dlib/Experiments/03-FaceMorph/result_face_morphed.jpg',np.uint8(imgMorph))
    cv2.waitKey(0)


In [2]:
test_03()