# genki-4k 数据集 人脸表情检测

### 定义face_cutter：识别人脸并裁剪

In [38]:
def face_cutter(file,k):
    import dlib
    import numpy as np
    import cv2
    # dlib预测器
    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor
    ('/Users/zhaoxuyan/Desktop/shape_predictor_68_face_landmarks.dat')
    # 读取图片路径
    img = cv2.imread(file,0)
    path_save = '/Users/zhaoxuyan/Desktop/genki-4k-cutted-num/'
    
    # dlib检测
    dets = detector(img, 1)
    
    try:
        if(len(dets) == 1):
            for m,d in enumerate(dets):
                # 计算矩阵大小
                pos_start = tuple([d.left(), d.top()])
                pos_end = tuple([d.right(), d.bottom()])

                print (k)
                # 计算矩形框大小
                height = d.bottom() - d.top()
                width = d.right() - d.left()

                # 根据人脸大小生成空的图像
                img_blank = np.zeros((height, width, 3), np.uint8)

                for i in range(height):
                    for j in range(width):
                        img_blank[i][j] = img[d.top() + i][d.left() + j]
                
                cv2.imwrite(path_save+str(k)+".jpg", img_blank)
        else:
            print ("未检测到人脸的图片：",file)
    except Exception:
        pass

In [39]:
import os  
path_read = "/Users/zhaoxuyan/Desktop/genki-4k"  #待读取的文件夹  
files=os.listdir(path_read)  
files.sort() #对读取的路径进行排序  
k=0
for file in files: 
    k=k+1
    face_cutter(os.path.join(path_read,file),k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file0019.jpg
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file0063.jpg
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file0147.jpg
148
149
150
151
152
153
154
155
156
157
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file0158.jpg
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
22

1511
1512
1513
1514
1515
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file1516.jpg
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file1555.jpg
1556
1557
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file1558.jpg
1559
1560
1561
1562
1563
1564
1565
1566
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file1567.jpg
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
166

2599
2600
2601
2602
2603
2604
2605
2606
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file2607.jpg
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file2636.jpg
2637
2638
2639
2640
2641
2642
2643
2644
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file2645.jpg
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file2686.jpg
2687
2688
2689
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file2690.jpg
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file2714.jpg
2715
2716
2717
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file2718.jpg
2719
未检测到人脸的图片： /Users/zhaoxu

3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file3612.jpg
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file3643.jpg
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file3644.jpg
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file3667.jpg
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file3678.jpg
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file3690.jpg
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
未检测到人脸的图片： /Users/zhaoxuyan/Desktop/genki-4k/file3724.jpg
3725
3726

### HOG特征提取

In [1]:
import dlib
import numpy as np
import cv2

def hog(image):
    hog = cv2.HOGDescriptor()
    h = hog.compute(image)
    return h

In [2]:
#提取目录下所有图片,更改尺寸后保存到另一目录  
from PIL import Image  
import os.path  
import glob  
def convertjpg(jpgfile,outdir,width=128,height=128):  
    img=Image.open(jpgfile)  
    try:  
        new_img=img.resize((width,height),Image.BILINEAR)     
        new_img.save(os.path.join(outdir,os.path.basename(jpgfile)))  
    except Exception as e:  
        print(e)  
for jpgfile in glob.glob("/Users/zhaoxuyan/Desktop/genki-4k-cutted-num/*.jpg"):  
    convertjpg(jpgfile,"/Users/zhaoxuyan/Desktop/genki-4k-resize-num")  

In [3]:
# #coding:utf8
# import os;

# def rename():
#         i=0
#         path="/Users/zhaoxuyan/Desktop/genki-4k-resize-2";
#         filelist=os.listdir(path)#该文件夹下所有的文件（包括文件夹）
#         for files in filelist:#遍历所有文件
#             i=i+1
#             Olddir=os.path.join(path,files);#原来的文件路径                
#             if os.path.isdir(Olddir):#如果是文件夹则跳过
#                     continue;
#             filename=os.path.splitext(files)[0];#文件名
#             filetype=os.path.splitext(files)[1];#文件扩展名
#             Newdir=os.path.join(path,str(i)+filetype);#新的文件路径
#             os.rename(Olddir,Newdir)#重命名
# rename()

### 得到data和target

In [4]:
X=[]
import os  
path="/Users/zhaoxuyan/Desktop/genki-4k-resize-num"  #待读取的文件夹  
files=os.listdir(path)  
files.sort(key= lambda x:int(x[:-4])) #对读取的路径进行排序  
for file in files:  
    im = cv2.imread(os.path.join(path,file))
    h = hog(im)
    X.append(h)

In [11]:
# 去掉了识别不出人脸的图像
y_1 =  [1 for x in range(1,2163)]  
y_0 = [0 for x in range(2163,3778)]
y = y_1 + y_0

In [12]:
X

[array([[0.15780333],
        [0.09530817],
        [0.10446513],
        ...,
        [0.03305323],
        [0.14681645],
        [0.38789633]], dtype=float32), array([[0.22365741],
        [0.04384351],
        [0.04641841],
        ...,
        [0.14098999],
        [0.17368503],
        [0.25184938]], dtype=float32), array([[0.06462917],
        [0.1105884 ],
        [0.06830955],
        ...,
        [0.03547978],
        [0.1095253 ],
        [0.3612323 ]], dtype=float32), array([[0.32165408],
        [0.2785221 ],
        [0.07438509],
        ...,
        [0.10221968],
        [0.10080477],
        [0.32061368]], dtype=float32), array([[0.18918733],
        [0.37945506],
        [0.3573875 ],
        ...,
        [0.01558123],
        [0.02385274],
        [0.11073008]], dtype=float32), array([[0.4611412 ],
        [0.22629966],
        [0.01308681],
        ...,
        [0.16401903],
        [0.16021459],
        [0.17627244]], dtype=float32), array([[0.3936635 ],
        [0.2

In [13]:
B=[]
for i in range(0,len(X)):
    A=X[i].reshape(1,-1)
    B.append(A[0])

In [14]:
B

[array([0.15780333, 0.09530817, 0.10446513, ..., 0.03305323, 0.14681645,
        0.38789633], dtype=float32),
 array([0.22365741, 0.04384351, 0.04641841, ..., 0.14098999, 0.17368503,
        0.25184938], dtype=float32),
 array([0.06462917, 0.1105884 , 0.06830955, ..., 0.03547978, 0.1095253 ,
        0.3612323 ], dtype=float32),
 array([0.32165408, 0.2785221 , 0.07438509, ..., 0.10221968, 0.10080477,
        0.32061368], dtype=float32),
 array([0.18918733, 0.37945506, 0.3573875 , ..., 0.01558123, 0.02385274,
        0.11073008], dtype=float32),
 array([0.4611412 , 0.22629966, 0.01308681, ..., 0.16401903, 0.16021459,
        0.17627244], dtype=float32),
 array([0.3936635 , 0.24174175, 0.027446  , ..., 0.01069873, 0.01165264,
        0.13824666], dtype=float32),
 array([0.312659  , 0.21681166, 0.19245537, ..., 0.29077289, 0.29077289,
        0.29077289], dtype=float32),
 array([0.12074927, 0.24263941, 0.11025273, ..., 0.01722742, 0.01571317,
        0.01556939], dtype=float32),
 array([0.

In [15]:
data = B
target = y

### 训练集验证集拆分

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
        data, target, test_size=0.25, random_state=0)

### sklearn SVM

In [17]:
from sklearn.svm import SVC
clf = SVC(kernel='linear')

### k折交叉验证

In [18]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train, cv=2)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.82 (+/- 0.01)


### 训练

In [19]:
from sklearn import metrics

def train_and_evaluate(clf, X_train, X_test, y_train, y_test):
    
    clf.fit(X_train, y_train)
    
    print ("Accuracy on training set:")
    print (clf.score(X_train, y_train))
    print ("Accuracy on testing set:")
    print (clf.score(X_test, y_test))
    
    y_pred = clf.predict(X_test)
    
    print ("Classification Report:")
    print (metrics.classification_report(y_test, y_pred))
    print ("Confusion Matrix:")
    print (metrics.confusion_matrix(y_test, y_pred))

In [20]:
train_and_evaluate(clf, X_train, X_test, y_train, y_test)

Accuracy on training set:
1.0
Accuracy on testing set:
0.8317460317460318
Classification Report:
             precision    recall  f1-score   support

          0       0.81      0.80      0.81       414
          1       0.85      0.85      0.85       531

avg / total       0.83      0.83      0.83       945

Confusion Matrix:
[[332  82]
 [ 77 454]]
